version: '3.4'

services:
  web:
    image: gymtracker
    build: .
    env_file:
      - .docker.env
    ports:
      - "8000:8000"
  postgres:
    image: postgres:15
    env_file:
      - .docker.env
    volumes:
      - "pgdata:/var/lib/postgresql/data"
volumes:
  pgdata:
