version: '3.4'

services:
  # web:
  #   image: gymtracker
  #   build: .
  #   env_file:
  #     - .env.
  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
volumes:
  pgdata:
