mod access_control;
mod add_exercise_set;
mod admin_page;
mod exercise_set;
mod graph_page;
mod history_page;
mod login_page;
mod main_page;
mod messages;
mod nav;
mod pr_page;
mod register_page;
mod stats_page;
mod user_page;

pub use access_control::*;
pub use add_exercise_set::*;
pub use admin_page::*;
pub use exercise_set::*;
pub use graph_page::*;
pub use history_page::*;
pub use login_page::*;
pub use main_page::*;
pub use messages::*;
pub use nav::*;
pub use pr_page::*;
pub use register_page::*;
pub use stats_page::*;
pub use user_page::*;
