//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "exercise_set")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: i32,
    pub name: String,
    pub reps: i32,
    pub weight: f32,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::login_user::Entity",
        from = "Column::UserId",
        to = "super::login_user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    LoginUser,
}

impl Related<super::login_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoginUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
