//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_info")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub user_id: i32,
    pub display_name: String,
    pub photo: Option<Vec<u8>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::login_user::Entity",
        from = "Column::UserId",
        to = "super::login_user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    LoginUser,
}

impl Related<super::login_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LoginUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
